/**
 * Expected World Cup 2026 starting XIs, formations, and managers.
 * Updated: 2026-05-31 — refresh squad data at least daily during tournament prep.
 */
import type { LineupPlayer } from "./formation-layout";

export const SQUAD_DATA_UPDATED = "2026-05-31";

export interface TeamSquadData {
  formation: string;
  manager: string;
  keyPlayer: { name: string; goals: number; assists: number };
  lineup: LineupPlayer[];
}

export const TEAM_SQUADS: Record<string, TeamSquadData> = {
  // Group A
  MEX: {
    formation: "4-3-3",
    manager: "Javier Aguirre",
    keyPlayer: { name: "Raúl Jiménez", goals: 0, assists: 0 },
    lineup: [
      { name: "Ochoa", number: 13, position: "GK" },
      { name: "Araujo", number: 2, position: "DF" },
      { name: "Montes", number: 3, position: "DF" },
      { name: "Vásquez", number: 5, position: "DF" },
      { name: "Gallardo", number: 23, position: "DF" },
      { name: "Álvarez", number: 8, position: "MF" },
      { name: "Pineda", number: 17, position: "MF" },
      { name: "Lozano", number: 22, position: "MF" },
      { name: "Jiménez", number: 9, position: "FW" },
      { name: "Antuna", number: 15, position: "FW" },
      { name: "Vega", number: 10, position: "FW" },
    ],
  },
  RSA: {
    formation: "4-2-3-1",
    manager: "Hugo Broos",
    keyPlayer: { name: "Percy Tau", goals: 0, assists: 0 },
    lineup: [
      { name: "Williams", number: 16, position: "GK" },
      { name: "Mokoena", number: 2, position: "DF" },
      { name: "Mothiba", number: 4, position: "DF" },
      { name: "De Reuck", number: 5, position: "DF" },
      { name: "Mashele", number: 3, position: "DF" },
      { name: "Mabula", number: 6, position: "MF" },
      { name: "Khumalo", number: 8, position: "MF" },
      { name: "Tau", number: 10, position: "MF" },
      { name: "Modiba", number: 11, position: "MF" },
      { name: "Dolly", number: 7, position: "MF" },
      { name: "Lorch", number: 9, position: "FW" },
    ],
  },
  KOR: {
    formation: "4-2-3-1",
    manager: "Hong Myung-bo",
    keyPlayer: { name: "Son Heung-min", goals: 0, assists: 0 },
    lineup: [
      { name: "Kim Seung-gyu", number: 21, position: "GK" },
      { name: "Kim Moon-hwan", number: 2, position: "DF" },
      { name: "Kim Min-jae", number: 4, position: "DF" },
      { name: "Kim Young-gwon", number: 19, position: "DF" },
      { name: "Hong Hyun-seok", number: 3, position: "DF" },
      { name: "Hwang In-beom", number: 6, position: "MF" },
      { name: "Lee Kang-in", number: 18, position: "MF" },
      { name: "Son", number: 7, position: "MF" },
      { name: "Hwang Hee-chan", number: 11, position: "MF" },
      { name: "Jeong Woo-yeong", number: 10, position: "MF" },
      { name: "Oh Hyeon-gyu", number: 9, position: "FW" },
    ],
  },
  CZE: {
    formation: "4-2-3-1",
    manager: "Ivan Hašek",
    keyPlayer: { name: "Patrik Schick", goals: 0, assists: 0 },
    lineup: [
      { name: "Staněk", number: 1, position: "GK" },
      { name: "Coufal", number: 5, position: "DF" },
      { name: "Krejčí", number: 4, position: "DF" },
      { name: "Holes", number: 3, position: "DF" },
      { name: "Zelezny", number: 2, position: "DF" },
      { name: "Souček", number: 22, position: "MF" },
      { name: "Stanek", number: 8, position: "MF" },
      { name: "Barák", number: 7, position: "MF" },
      { name: "Chytil", number: 11, position: "MF" },
      { name: "Krejčí", number: 10, position: "MF" },
      { name: "Schick", number: 9, position: "FW" },
    ],
  },
  // Group B
  CAN: {
    formation: "4-3-3",
    manager: "Jesse Marsch",
    keyPlayer: { name: "Alphonso Davies", goals: 0, assists: 0 },
    lineup: [
      { name: "St. Clair", number: 1, position: "GK" },
      { name: "Johnston", number: 2, position: "DF" },
      { name: "Miller", number: 4, position: "DF" },
      { name: "Cornelius", number: 5, position: "DF" },
      { name: "Davies", number: 3, position: "DF" },
      { name: "Eustáquio", number: 7, position: "MF" },
      { name: "Osorio", number: 8, position: "MF" },
      { name: "Kone", number: 6, position: "MF" },
      { name: "Buchanan", number: 11, position: "FW" },
      { name: "Larin", number: 9, position: "FW" },
      { name: "David", number: 10, position: "FW" },
    ],
  },
  BIH: {
    formation: "4-3-3",
    manager: "Sergej Barbarez",
    keyPlayer: { name: "Edin Džeko", goals: 0, assists: 0 },
    lineup: [
      { name: "Šehić", number: 1, position: "GK" },
      { name: "Kolasinac", number: 5, position: "DF" },
      { name: "Hadžikadunić", number: 4, position: "DF" },
      { name: "Tahić", number: 3, position: "DF" },
      { name: "Dedić", number: 2, position: "DF" },
      { name: "Bašić", number: 8, position: "MF" },
      { name: "Prcić", number: 6, position: "MF" },
      { name: "Todorović", number: 10, position: "MF" },
      { name: "Džeko", number: 9, position: "FW" },
      { name: "Hodžić", number: 11, position: "FW" },
      { name: "Bajraktarević", number: 7, position: "FW" },
    ],
  },
  QAT: {
    formation: "4-2-3-1",
    manager: "Julen Lopetegui",
    keyPlayer: { name: "Almoez Ali", goals: 0, assists: 0 },
    lineup: [
      { name: "Barsham", number: 1, position: "GK" },
      { name: "Ro-Ro", number: 2, position: "DF" },
      { name: "Mendy", number: 5, position: "DF" },
      { name: "Hassan", number: 4, position: "DF" },
      { name: "Ahmed", number: 3, position: "DF" },
      { name: "Hassan", number: 6, position: "MF" },
      { name: "Boudiaf", number: 8, position: "MF" },
      { name: "Afif", number: 11, position: "MF" },
      { name: "Al-Haydos", number: 10, position: "MF" },
      { name: "Muntari", number: 7, position: "MF" },
      { name: "Ali", number: 9, position: "FW" },
    ],
  },
  SUI: {
    formation: "3-4-3",
    manager: "Murat Yakin",
    keyPlayer: { name: "Granit Xhaka", goals: 0, assists: 0 },
    lineup: [
      { name: "Sommer", number: 1, position: "GK" },
      { name: "Schär", number: 5, position: "DF" },
      { name: "Akanji", number: 4, position: "DF" },
      { name: "Rodriguez", number: 3, position: "DF" },
      { name: "Rieder", number: 2, position: "MF" },
      { name: "Xhaka", number: 10, position: "MF" },
      { name: "Freuler", number: 8, position: "MF" },
      { name: "Bachmann", number: 11, position: "MF" },
      { name: "Vargas", number: 7, position: "FW" },
      { name: "Embolo", number: 9, position: "FW" },
      { name: "Ndoye", number: 14, position: "FW" },
    ],
  },
  // Group C
  BRA: {
    formation: "4-2-3-1",
    manager: "Carlo Ancelotti",
    keyPlayer: { name: "Vinícius Júnior", goals: 0, assists: 0 },
    lineup: [
      { name: "Alisson", number: 1, position: "GK" },
      { name: "Danilo", number: 2, position: "DF" },
      { name: "Marquinhos", number: 4, position: "DF" },
      { name: "Bastos", number: 3, position: "DF" },
      { name: "Wendell", number: 6, position: "DF" },
      { name: "André", number: 5, position: "MF" },
      { name: "Bruno G.", number: 8, position: "MF" },
      { name: "Rodrygo", number: 11, position: "MF" },
      { name: "Raphinha", number: 10, position: "MF" },
      { name: "Vinícius", number: 7, position: "MF" },
      { name: "Endrick", number: 9, position: "FW" },
    ],
  },
  MAR: {
    formation: "4-1-4-1",
    manager: "Walid Regragui",
    keyPlayer: { name: "Achraf Hakimi", goals: 0, assists: 0 },
    lineup: [
      { name: "Bono", number: 1, position: "GK" },
      { name: "Hakimi", number: 2, position: "DF" },
      { name: "Saïss", number: 4, position: "DF" },
      { name: "Aguerd", number: 5, position: "DF" },
      { name: "Mazraoui", number: 3, position: "DF" },
      { name: "Amrabat", number: 6, position: "MF" },
      { name: "Ounahi", number: 8, position: "MF" },
      { name: "Ziyech", number: 10, position: "MF" },
      { name: "Boufal", number: 11, position: "MF" },
      { name: "Harit", number: 7, position: "MF" },
      { name: "En-Nesyri", number: 9, position: "FW" },
    ],
  },
  HAI: {
    formation: "4-4-2",
    manager: "Sébastien Migné",
    keyPlayer: { name: "Frantzdy Pierrot", goals: 0, assists: 0 },
    lineup: [
      { name: "Placide", number: 1, position: "GK" },
      { name: "Gedeon", number: 2, position: "DF" },
      { name: "Lafrance", number: 4, position: "DF" },
      { name: "Jean-Baptiste", number: 5, position: "DF" },
      { name: "Duverger", number: 3, position: "DF" },
      { name: "Jean", number: 7, position: "MF" },
      { name: "Alcénat", number: 8, position: "MF" },
      { name: "Derrico", number: 6, position: "MF" },
      { name: "Nazon", number: 11, position: "MF" },
      { name: "Pierrot", number: 9, position: "FW" },
      { name: "Coradin", number: 10, position: "FW" },
    ],
  },
  SCO: {
    formation: "3-5-2",
    manager: "Steve Clarke",
    keyPlayer: { name: "Scott McTominay", goals: 0, assists: 0 },
    lineup: [
      { name: "Gordon", number: 1, position: "GK" },
      { name: "Hanley", number: 5, position: "DF" },
      { name: "Porteous", number: 4, position: "DF" },
      { name: "Souttar", number: 3, position: "DF" },
      { name: "Ralston", number: 2, position: "MF" },
      { name: "McTominay", number: 8, position: "MF" },
      { name: "McGinn", number: 10, position: "MF" },
      { name: "Gilmour", number: 6, position: "MF" },
      { name: "Robertson", number: 11, position: "MF" },
      { name: "Dykes", number: 9, position: "FW" },
      { name: "Shankland", number: 14, position: "FW" },
    ],
  },
  // Group D
  USA: {
    formation: "4-3-3",
    manager: "Mauricio Pochettino",
    keyPlayer: { name: "Christian Pulisic", goals: 0, assists: 0 },
    lineup: [
      { name: "Turner", number: 1, position: "GK" },
      { name: "Dest", number: 2, position: "DF" },
      { name: "Ream", number: 4, position: "DF" },
      { name: "Robinson", number: 5, position: "DF" },
      { name: "Robinson", number: 3, position: "DF" },
      { name: "Adams", number: 6, position: "MF" },
      { name: "Musah", number: 8, position: "MF" },
      { name: "McKennie", number: 10, position: "MF" },
      { name: "Pulisic", number: 11, position: "FW" },
      { name: "Balogun", number: 9, position: "FW" },
      { name: "Weah", number: 7, position: "FW" },
    ],
  },
  PAR: {
    formation: "4-4-2",
    manager: "Gustavo Alfaro",
    keyPlayer: { name: "Miguel Almirón", goals: 0, assists: 0 },
    lineup: [
      { name: "Silva", number: 1, position: "GK" },
      { name: "Vallejo", number: 2, position: "DF" },
      { name: "Gómez", number: 4, position: "DF" },
      { name: "Alderete", number: 5, position: "DF" },
      { name: "Espínola", number: 3, position: "DF" },
      { name: "Almirón", number: 10, position: "MF" },
      { name: "Sánchez", number: 8, position: "MF" },
      { name: "Kaku", number: 7, position: "MF" },
      { name: "Romero", number: 11, position: "MF" },
      { name: "Santamaría", number: 9, position: "FW" },
      { name: "González", number: 18, position: "FW" },
    ],
  },
  AUS: {
    formation: "4-2-3-1",
    manager: "Graham Arnold",
    keyPlayer: { name: "Mathew Ryan", goals: 0, assists: 0 },
    lineup: [
      { name: "Ryan", number: 1, position: "GK" },
      { name: "Atkinson", number: 2, position: "DF" },
      { name: "Souttar", number: 4, position: "DF" },
      { name: "Rowles", number: 5, position: "DF" },
      { name: "Behich", number: 3, position: "DF" },
      { name: "Irvine", number: 6, position: "MF" },
      { name: "Metcalfe", number: 8, position: "MF" },
      { name: "Goodwin", number: 11, position: "MF" },
      { name: "Leckie", number: 7, position: "MF" },
      { name: "Tilio", number: 10, position: "MF" },
      { name: "Maclaren", number: 9, position: "FW" },
    ],
  },
  TUR: {
    formation: "4-2-3-1",
    manager: "Vincenzo Montella",
    keyPlayer: { name: "Hakan Çalhanoğlu", goals: 0, assists: 0 },
    lineup: [
      { name: "Günok", number: 1, position: "GK" },
      { name: "Zeki", number: 2, position: "DF" },
      { name: "Demiral", number: 4, position: "DF" },
      { name: "Söyüncü", number: 5, position: "DF" },
      { name: "Kadioglu", number: 3, position: "DF" },
      { name: "Yilmaz", number: 6, position: "MF" },
      { name: "Çalhanoğlu", number: 10, position: "MF" },
      { name: "Yildiz", number: 11, position: "MF" },
      { name: "Güler", number: 7, position: "MF" },
      { name: "Aktürkoğlu", number: 8, position: "MF" },
      { name: "Yildirim", number: 9, position: "FW" },
    ],
  },
  // Group E
  GER: {
    formation: "4-2-3-1",
    manager: "Julian Nagelsmann",
    keyPlayer: { name: "Jamal Musiala", goals: 0, assists: 0 },
    lineup: [
      { name: "Neuer", number: 1, position: "GK" },
      { name: "Kimmich", number: 6, position: "DF" },
      { name: "Rüdiger", number: 2, position: "DF" },
      { name: "Tah", number: 4, position: "DF" },
      { name: "Mittelstädt", number: 3, position: "DF" },
      { name: "Andrich", number: 5, position: "MF" },
      { name: "Kroos", number: 8, position: "MF" },
      { name: "Musiala", number: 10, position: "MF" },
      { name: "Wirtz", number: 11, position: "MF" },
      { name: "Sané", number: 7, position: "MF" },
      { name: "Füllkrug", number: 9, position: "FW" },
    ],
  },
  CUW: {
    formation: "4-3-3",
    manager: "Dick Advocaat",
    keyPlayer: { name: "Leandro Bacuna", goals: 0, assists: 0 },
    lineup: [
      { name: "Rosa", number: 1, position: "GK" },
      { name: "Martina", number: 2, position: "DF" },
      { name: "Lelieveld", number: 4, position: "DF" },
      { name: "Baas", number: 5, position: "DF" },
      { name: "Koch", number: 3, position: "DF" },
      { name: "Bacuna", number: 10, position: "MF" },
      { name: "Janga", number: 8, position: "MF" },
      { name: "Maria", number: 6, position: "MF" },
      { name: "Antonia", number: 11, position: "FW" },
      { name: "Janga", number: 9, position: "FW" },
      { name: "Hooiveld", number: 7, position: "FW" },
    ],
  },
  CIV: {
    formation: "4-3-3",
    manager: "Emerse Faé",
    keyPlayer: { name: "Nicolas Pépé", goals: 0, assists: 0 },
    lineup: [
      { name: "Fadiga", number: 1, position: "GK" },
      { name: "Konan", number: 2, position: "DF" },
      { name: "Boly", number: 4, position: "DF" },
      { name: "Kouakou", number: 5, position: "DF" },
      { name: "Singo", number: 3, position: "DF" },
      { name: "Seri", number: 6, position: "MF" },
      { name: "Kessié", number: 8, position: "MF" },
      { name: "Zaha", number: 10, position: "MF" },
      { name: "Pépé", number: 11, position: "FW" },
      { name: "Kouamé", number: 9, position: "FW" },
      { name: "Adingra", number: 7, position: "FW" },
    ],
  },
  ECU: {
    formation: "4-4-2",
    manager: "Sebastián Beccacece",
    keyPlayer: { name: "Enner Valencia", goals: 0, assists: 0 },
    lineup: [
      { name: "Domínguez", number: 1, position: "GK" },
      { name: "Preciado", number: 2, position: "DF" },
      { name: "Torres", number: 4, position: "DF" },
      { name: "Hincapié", number: 5, position: "DF" },
      { name: "Estupiñán", number: 3, position: "DF" },
      { name: "Caicedo", number: 6, position: "MF" },
      { name: "Gruezo", number: 8, position: "MF" },
      { name: "Plata", number: 11, position: "MF" },
      { name: "Ibarra", number: 7, position: "MF" },
      { name: "Valencia", number: 9, position: "FW" },
      { name: "Estrada", number: 10, position: "FW" },
    ],
  },
  // Group F
  NED: {
    formation: "4-3-3",
    manager: "Ronald Koeman",
    keyPlayer: { name: "Memphis Depay", goals: 0, assists: 0 },
    lineup: [
      { name: "Verbruggen", number: 1, position: "GK" },
      { name: "Dumfries", number: 2, position: "DF" },
      { name: "Van Dijk", number: 4, position: "DF" },
      { name: "De Ligt", number: 5, position: "DF" },
      { name: "Blind", number: 3, position: "DF" },
      { name: "Reijnders", number: 8, position: "MF" },
      { name: "Wijnaldum", number: 6, position: "MF" },
      { name: "Simons", number: 10, position: "MF" },
      { name: "Gakpo", number: 11, position: "FW" },
      { name: "Depay", number: 9, position: "FW" },
      { name: "Bergwijn", number: 7, position: "FW" },
    ],
  },
  JPN: {
    formation: "4-2-3-1",
    manager: "Hajime Moriyasu",
    keyPlayer: { name: "Kaoru Mitoma", goals: 0, assists: 0 },
    lineup: [
      { name: "Suzuki", number: 1, position: "GK" },
      { name: "Ito", number: 2, position: "DF" },
      { name: "Tomiyasu", number: 4, position: "DF" },
      { name: "Taniguchi", number: 5, position: "DF" },
      { name: "Ito", number: 3, position: "DF" },
      { name: "Endo", number: 6, position: "MF" },
      { name: "Morita", number: 8, position: "MF" },
      { name: "Mitoma", number: 11, position: "MF" },
      { name: "Kubo", number: 10, position: "MF" },
      { name: "Minamino", number: 7, position: "MF" },
      { name: "Osako", number: 9, position: "FW" },
    ],
  },
  SWE: {
    formation: "4-4-2",
    manager: "Jon Dahl Tomasson",
    keyPlayer: { name: "Alexander Isak", goals: 0, assists: 0 },
    lineup: [
      { name: "Viktor", number: 1, position: "GK" },
      { name: "Krafth", number: 2, position: "DF" },
      { name: "Lindelöf", number: 4, position: "DF" },
      { name: "Nelson", number: 5, position: "DF" },
      { name: "Augustinsson", number: 3, position: "DF" },
      { name: "Kulusevski", number: 10, position: "MF" },
      { name: "Olsson", number: 8, position: "MF" },
      { name: "Forsberg", number: 7, position: "MF" },
      { name: "Elanga", number: 11, position: "MF" },
      { name: "Isak", number: 9, position: "FW" },
      { name: "Gyökeres", number: 14, position: "FW" },
    ],
  },
  TUN: {
    formation: "4-3-3",
    manager: "Sabri Lamouchi",
    keyPlayer: { name: "Youssef Msakni", goals: 0, assists: 0 },
    lineup: [
      { name: "Dahmen", number: 1, position: "GK" },
      { name: "Draeger", number: 2, position: "DF" },
      { name: "Meriah", number: 4, position: "DF" },
      { name: "Talbi", number: 5, position: "DF" },
      { name: "Laabidi", number: 3, position: "DF" },
      { name: "Laidouni", number: 6, position: "MF" },
      { name: "Skhiri", number: 8, position: "MF" },
      { name: "Msakni", number: 10, position: "MF" },
      { name: "Khazri", number: 11, position: "FW" },
      { name: "Jebali", number: 9, position: "FW" },
      { name: "Sliti", number: 7, position: "FW" },
    ],
  },
  // Group G
  BEL: {
    formation: "4-2-3-3",
    manager: "Rudi Garcia",
    keyPlayer: { name: "Kevin De Bruyne", goals: 0, assists: 0 },
    lineup: [
      { name: "Casteels", number: 1, position: "GK" },
      { name: "Castagne", number: 2, position: "DF" },
      { name: "Vertonghen", number: 4, position: "DF" },
      { name: "Theate", number: 5, position: "DF" },
      { name: "De Cuyper", number: 3, position: "DF" },
      { name: "Tielemans", number: 6, position: "MF" },
      { name: "De Bruyne", number: 10, position: "MF" },
      { name: "Doku", number: 11, position: "MF" },
      { name: "Trossard", number: 7, position: "MF" },
      { name: "Openda", number: 9, position: "MF" },
      { name: "Lukaku", number: 14, position: "FW" },
    ],
  },
  EGY: {
    formation: "4-2-3-1",
    manager: "Hossam Hassan",
    keyPlayer: { name: "Mohamed Salah", goals: 0, assists: 0 },
    lineup: [
      { name: "El Shenawy", number: 1, position: "GK" },
      { name: "Hany", number: 2, position: "DF" },
      { name: "Hegazi", number: 4, position: "DF" },
      { name: "Abdelmonem", number: 5, position: "DF" },
      { name: "Hamdy", number: 3, position: "DF" },
      { name: "El Neny", number: 6, position: "MF" },
      { name: "Fathy", number: 8, position: "MF" },
      { name: "Salah", number: 10, position: "MF" },
      { name: "Trezeguet", number: 11, position: "MF" },
      { name: "Marmoush", number: 7, position: "MF" },
      { name: "Hassan", number: 9, position: "FW" },
    ],
  },
  IRN: {
    formation: "4-1-4-1",
    manager: "Amir Ghalenoei",
    keyPlayer: { name: "Sardar Azmoun", goals: 0, assists: 0 },
    lineup: [
      { name: "Beiranvand", number: 1, position: "GK" },
      { name: "Rezaeian", number: 2, position: "DF" },
      { name: "Kanani", number: 4, position: "DF" },
      { name: "Hosseini", number: 5, position: "DF" },
      { name: "Mohammadi", number: 3, position: "DF" },
      { name: "Ezatolahi", number: 6, position: "MF" },
      { name: "Ghoddos", number: 8, position: "MF" },
      { name: "Jahanbakhsh", number: 11, position: "MF" },
      { name: "Taremi", number: 10, position: "MF" },
      { name: "Shojaei", number: 7, position: "MF" },
      { name: "Azmoun", number: 9, position: "FW" },
    ],
  },
  NZL: {
    formation: "4-4-2",
    manager: "Darren Bazeley",
    keyPlayer: { name: "Chris Wood", goals: 0, assists: 0 },
    lineup: [
      { name: "Mead", number: 1, position: "GK" },
      { name: "Boxall", number: 2, position: "DF" },
      { name: "Smith", number: 4, position: "DF" },
      { name: "Kelly", number: 5, position: "DF" },
      { name: "Wagner", number: 3, position: "DF" },
      { name: "Singh", number: 7, position: "MF" },
      { name: "Garvey", number: 8, position: "MF" },
      { name: "Just", number: 6, position: "MF" },
      { name: "Thomas", number: 11, position: "MF" },
      { name: "Wood", number: 9, position: "FW" },
      { name: "Garbett", number: 10, position: "FW" },
    ],
  },
  // Group H
  ESP: {
    formation: "4-3-3",
    manager: "Luis de la Fuente",
    keyPlayer: { name: "Lamine Yamal", goals: 0, assists: 0 },
    lineup: [
      { name: "Simón", number: 1, position: "GK" },
      { name: "Carvajal", number: 2, position: "DF" },
      { name: "Le Normand", number: 4, position: "DF" },
      { name: "Laporte", number: 5, position: "DF" },
      { name: "Cucurella", number: 3, position: "DF" },
      { name: "Rodri", number: 6, position: "MF" },
      { name: "Olmo", number: 8, position: "MF" },
      { name: "Pedri", number: 10, position: "MF" },
      { name: "Yamal", number: 11, position: "FW" },
      { name: "Morata", number: 9, position: "FW" },
      { name: "Williams", number: 7, position: "FW" },
    ],
  },
  CPV: {
    formation: "4-4-2",
    manager: "Bubista",
    keyPlayer: { name: "Ryan Mendes", goals: 0, assists: 0 },
    lineup: [
      { name: "Vozinha", number: 1, position: "GK" },
      { name: "Stopira", number: 2, position: "DF" },
      { name: "Pinto", number: 4, position: "DF" },
      { name: "Dias", number: 5, position: "DF" },
      { name: "Monteiro", number: 3, position: "DF" },
      { name: "Mendes", number: 11, position: "MF" },
      { name: "Semedo", number: 8, position: "MF" },
      { name: "Pires", number: 6, position: "MF" },
      { name: "Cabral", number: 7, position: "MF" },
      { name: "Rocha", number: 9, position: "FW" },
      { name: "Geraldo", number: 10, position: "FW" },
    ],
  },
  SAU: {
    formation: "4-2-3-1",
    manager: "Fabio Cannavaro",
    keyPlayer: { name: "Salem Al-Dawsari", goals: 0, assists: 0 },
    lineup: [
      { name: "Al-Owais", number: 1, position: "GK" },
      { name: "Al-Breik", number: 2, position: "DF" },
      { name: "Al-Amri", number: 4, position: "DF" },
      { name: "Al-Tambakti", number: 5, position: "DF" },
      { name: "Al-Shahrani", number: 3, position: "DF" },
      { name: "Al-Khaibari", number: 6, position: "MF" },
      { name: "Al-Faraj", number: 8, position: "MF" },
      { name: "Al-Dawsari", number: 10, position: "MF" },
      { name: "Al-Shehri", number: 11, position: "MF" },
      { name: "Al-Burayk", number: 7, position: "MF" },
      { name: "Al-Buraikan", number: 9, position: "FW" },
    ],
  },
  URU: {
    formation: "4-4-2",
    manager: "Marcelo Bielsa",
    keyPlayer: { name: "Federico Valverde", goals: 0, assists: 0 },
    lineup: [
      { name: "Rochet", number: 1, position: "GK" },
      { name: "Nández", number: 2, position: "DF" },
      { name: "Araujo", number: 4, position: "DF" },
      { name: "Olivera", number: 5, position: "DF" },
      { name: "Viña", number: 3, position: "DF" },
      { name: "Valverde", number: 8, position: "MF" },
      { name: "Ugarte", number: 6, position: "MF" },
      { name: "Pellistri", number: 11, position: "MF" },
      { name: "De la Cruz", number: 7, position: "MF" },
      { name: "Núñez", number: 9, position: "FW" },
      { name: "Suárez", number: 10, position: "FW" },
    ],
  },
  // Group I
  FRA: {
    formation: "4-3-3",
    manager: "Didier Deschamps",
    keyPlayer: { name: "Kylian Mbappé", goals: 0, assists: 0 },
    lineup: [
      { name: "Maignan", number: 1, position: "GK" },
      { name: "Koundé", number: 2, position: "DF" },
      { name: "Saliba", number: 4, position: "DF" },
      { name: "Upamecano", number: 5, position: "DF" },
      { name: "Hernandez", number: 3, position: "DF" },
      { name: "Tchouaméni", number: 6, position: "MF" },
      { name: "Camavinga", number: 8, position: "MF" },
      { name: "Griezmann", number: 10, position: "MF" },
      { name: "Mbappé", number: 11, position: "FW" },
      { name: "Giroud", number: 9, position: "FW" },
      { name: "Dembélé", number: 7, position: "FW" },
    ],
  },
  SEN: {
    formation: "4-3-3",
    manager: "Pape Thiaw",
    keyPlayer: { name: "Sadio Mané", goals: 0, assists: 0 },
    lineup: [
      { name: "Mendy", number: 1, position: "GK" },
      { name: "Sabaly", number: 2, position: "DF" },
      { name: "Koulibaly", number: 4, position: "DF" },
      { name: "Diallo", number: 5, position: "DF" },
      { name: "Jakobs", number: 3, position: "DF" },
      { name: "Gueye", number: 6, position: "MF" },
      { name: "Ndiaye", number: 8, position: "MF" },
      { name: "Mané", number: 10, position: "MF" },
      { name: "Sarr", number: 11, position: "FW" },
      { name: "Jackson", number: 9, position: "FW" },
      { name: "Diouf", number: 7, position: "FW" },
    ],
  },
  IRQ: {
    formation: "4-2-3-1",
    manager: "Graham Arnold",
    keyPlayer: { name: "Aymen Hussein", goals: 0, assists: 0 },
    lineup: [
      { name: "Hassan", number: 1, position: "GK" },
      { name: "Raouf", number: 2, position: "DF" },
      { name: "Adnan", number: 4, position: "DF" },
      { name: "Mansour", number: 5, position: "DF" },
      { name: "Fattah", number: 3, position: "DF" },
      { name: "Amjad", number: 6, position: "MF" },
      { name: "Alaa", number: 8, position: "MF" },
      { name: "Hussein", number: 10, position: "MF" },
      { name: "Mahmoud", number: 11, position: "MF" },
      { name: "Ali", number: 7, position: "MF" },
      { name: "Hussein", number: 9, position: "FW" },
    ],
  },
  NOR: {
    formation: "4-3-3",
    manager: "Ståle Solbakken",
    keyPlayer: { name: "Erling Haaland", goals: 0, assists: 0 },
    lineup: [
      { name: "Nyland", number: 1, position: "GK" },
      { name: "Ryerson", number: 2, position: "DF" },
      { name: "Hauge", number: 4, position: "DF" },
      { name: "Grepstad", number: 5, position: "DF" },
      { name: "Wolfe", number: 3, position: "DF" },
      { name: "Berge", number: 6, position: "MF" },
      { name: "Aursnes", number: 8, position: "MF" },
      { name: "Ødegaard", number: 10, position: "MF" },
      { name: "Haaland", number: 9, position: "FW" },
      { name: "Sørloth", number: 11, position: "FW" },
      { name: "Berg", number: 7, position: "FW" },
    ],
  },
  // Group J
  ARG: {
    formation: "4-3-3",
    manager: "Lionel Scaloni",
    keyPlayer: { name: "Lionel Messi", goals: 0, assists: 0 },
    lineup: [
      { name: "Martínez", number: 23, position: "GK" },
      { name: "Molina", number: 26, position: "DF" },
      { name: "Romero", number: 13, position: "DF" },
      { name: "Otamendi", number: 19, position: "DF" },
      { name: "Tagliafico", number: 3, position: "DF" },
      { name: "De Paul", number: 7, position: "MF" },
      { name: "Fernández", number: 24, position: "MF" },
      { name: "Mac Allister", number: 20, position: "MF" },
      { name: "Messi", number: 10, position: "FW" },
      { name: "Álvarez", number: 9, position: "FW" },
      { name: "Di María", number: 11, position: "FW" },
    ],
  },
  ALG: {
    formation: "4-3-3",
    manager: "Djamel Belmadi",
    keyPlayer: { name: "Riyad Mahrez", goals: 0, assists: 0 },
    lineup: [
      { name: "Mandrea", number: 1, position: "GK" },
      { name: "Atal", number: 2, position: "DF" },
      { name: "Mandi", number: 4, position: "DF" },
      { name: "Delort", number: 5, position: "DF" },
      { name: "Benlamri", number: 3, position: "DF" },
      { name: "Bennacer", number: 6, position: "MF" },
      { name: "Aouar", number: 8, position: "MF" },
      { name: "Mahrez", number: 10, position: "MF" },
      { name: "Bounedjah", number: 9, position: "FW" },
      { name: "Belaïli", number: 11, position: "FW" },
      { name: "Amoura", number: 7, position: "FW" },
    ],
  },
  AUT: {
    formation: "4-2-3-1",
    manager: "Ralf Rangnick",
    keyPlayer: { name: "Marcel Sabitzer", goals: 0, assists: 0 },
    lineup: [
      { name: "Pentz", number: 1, position: "GK" },
      { name: "Posch", number: 2, position: "DF" },
      { name: "Alaba", number: 4, position: "DF" },
      { name: "Lienhart", number: 5, position: "DF" },
      { name: "Mwene", number: 3, position: "DF" },
      { name: "Sabitzer", number: 6, position: "MF" },
      { name: "Seiwald", number: 8, position: "MF" },
      { name: "Baumgartner", number: 10, position: "MF" },
      { name: "Grillitsch", number: 11, position: "MF" },
      { name: "Arnautović", number: 7, position: "MF" },
      { name: "Gregoritsch", number: 9, position: "FW" },
    ],
  },
  JOR: {
    formation: "4-4-2",
    manager: "Husam Al-Mulla",
    keyPlayer: { name: "Musa Al-Taamari", goals: 0, assists: 0 },
    lineup: [
      { name: "Abu Laila", number: 1, position: "GK" },
      { name: "Al-Naimat", number: 2, position: "DF" },
      { name: "Al-Ajarmeh", number: 4, position: "DF" },
      { name: "Abdel-Rahman", number: 5, position: "DF" },
      { name: "Al-Bari", number: 3, position: "DF" },
      { name: "Al-Taamari", number: 10, position: "MF" },
      { name: "Rawashdeh", number: 8, position: "MF" },
      { name: "Al-Rashdan", number: 6, position: "MF" },
      { name: "Al-Naimat", number: 11, position: "MF" },
      { name: "Abdel-Rahman", number: 9, position: "FW" },
      { name: "Al-Maharmeh", number: 7, position: "FW" },
    ],
  },
  // Group K
  POR: {
    formation: "4-3-3",
    manager: "Roberto Martínez",
    keyPlayer: { name: "Cristiano Ronaldo", goals: 0, assists: 0 },
    lineup: [
      { name: "Costa", number: 1, position: "GK" },
      { name: "Nunes", number: 2, position: "DF" },
      { name: "Dias", number: 4, position: "DF" },
      { name: "Inácio", number: 5, position: "DF" },
      { name: "Mendes", number: 3, position: "DF" },
      { name: "Vitinha", number: 8, position: "MF" },
      { name: "Neves", number: 6, position: "MF" },
      { name: "Fernandes", number: 10, position: "MF" },
      { name: "Conceição", number: 11, position: "FW" },
      { name: "Ronaldo", number: 9, position: "FW" },
      { name: "Leão", number: 7, position: "FW" },
    ],
  },
  COD: {
    formation: "4-2-3-1",
    manager: "Sébastien Desabre",
    keyPlayer: { name: "Yoane Wissa", goals: 0, assists: 0 },
    lineup: [
      { name: "Mpeko", number: 1, position: "GK" },
      { name: "Muyuma", number: 2, position: "DF" },
      { name: "Mukau", number: 4, position: "DF" },
      { name: "Mbock", number: 5, position: "DF" },
      { name: "Masuaku", number: 3, position: "DF" },
      { name: "Makiadi", number: 6, position: "MF" },
      { name: "Mpeko", number: 8, position: "MF" },
      { name: "Bakambu", number: 10, position: "MF" },
      { name: "Wissa", number: 11, position: "MF" },
      { name: "Bope", number: 7, position: "MF" },
      { name: "Mbo", number: 9, position: "FW" },
    ],
  },
  UZB: {
    formation: "4-4-2",
    manager: "Srečko Katanec",
    keyPlayer: { name: "Eldor Shomurodov", goals: 0, assists: 0 },
    lineup: [
      { name: "Nesterov", number: 1, position: "GK" },
      { name: "Shukurov", number: 2, position: "DF" },
      { name: "Denisov", number: 4, position: "DF" },
      { name: "Khusanov", number: 5, position: "DF" },
      { name: "Alikulov", number: 3, position: "DF" },
      { name: "Masharipov", number: 8, position: "MF" },
      { name: "Jalilov", number: 6, position: "MF" },
      { name: "Khamdamov", number: 11, position: "MF" },
      { name: "Shomurodov", number: 9, position: "FW" },
      { name: "Turgunboev", number: 7, position: "FW" },
    ],
  },
  COL: {
    formation: "4-2-3-1",
    manager: "Néstor Lorenzo",
    keyPlayer: { name: "James Rodríguez", goals: 0, assists: 0 },
    lineup: [
      { name: "Mármol", number: 1, position: "GK" },
      { name: "Muñoz", number: 2, position: "DF" },
      { name: "Sánchez", number: 4, position: "DF" },
      { name: "Lucumí", number: 5, position: "DF" },
      { name: "Mojica", number: 3, position: "DF" },
      { name: "Barrios", number: 6, position: "MF" },
      { name: "Ríos", number: 8, position: "MF" },
      { name: "James", number: 10, position: "MF" },
      { name: "Díaz", number: 11, position: "MF" },
      { name: "Arias", number: 7, position: "MF" },
      { name: "Borré", number: 9, position: "FW" },
    ],
  },
  // Group L
  ENG: {
    formation: "4-2-3-1",
    manager: "Thomas Tuchel",
    keyPlayer: { name: "Harry Kane", goals: 0, assists: 0 },
    lineup: [
      { name: "Pickford", number: 1, position: "GK" },
      { name: "Walker", number: 2, position: "DF" },
      { name: "Stones", number: 4, position: "DF" },
      { name: "Guehi", number: 5, position: "DF" },
      { name: "Shaw", number: 3, position: "DF" },
      { name: "Rice", number: 6, position: "MF" },
      { name: "Mainoo", number: 6, position: "MF" },
      { name: "Bellingham", number: 10, position: "MF" },
      { name: "Foden", number: 11, position: "MF" },
      { name: "Saka", number: 7, position: "MF" },
      { name: "Kane", number: 9, position: "FW" },
    ],
  },
  CRO: {
    formation: "4-3-3",
    manager: "Zlatko Dalić",
    keyPlayer: { name: "Luka Modrić", goals: 0, assists: 0 },
    lineup: [
      { name: "Livaković", number: 1, position: "GK" },
      { name: "Stanišić", number: 2, position: "DF" },
      { name: "Gvardiol", number: 4, position: "DF" },
      { name: "Šutalo", number: 5, position: "DF" },
      { name: "Sosa", number: 3, position: "DF" },
      { name: "Modrić", number: 10, position: "MF" },
      { name: "Brozović", number: 6, position: "MF" },
      { name: "Kovačić", number: 8, position: "MF" },
      { name: "Perišić", number: 11, position: "FW" },
      { name: "Kramarić", number: 9, position: "FW" },
      { name: "Rebić", number: 7, position: "FW" },
    ],
  },
  GHA: {
    formation: "4-2-3-1",
    manager: "Otto Addo",
    keyPlayer: { name: "Mohammed Kudus", goals: 0, assists: 0 },
    lineup: [
      { name: "Ati-Zigi", number: 1, position: "GK" },
      { name: "Osei", number: 2, position: "DF" },
      { name: "Amartey", number: 4, position: "DF" },
      { name: "Djiku", number: 5, position: "DF" },
      { name: "Baba", number: 3, position: "DF" },
      { name: "Partey", number: 6, position: "MF" },
      { name: "Salisu", number: 8, position: "MF" },
      { name: "Kudus", number: 10, position: "MF" },
      { name: "Semenyo", number: 11, position: "MF" },
      { name: "Acheampong", number: 7, position: "MF" },
      { name: "Jordan", number: 9, position: "FW" },
    ],
  },
  PAN: {
    formation: "5-3-2",
    manager: "Thomas Christiansen",
    keyPlayer: { name: "Adalberto Carrasquilla", goals: 0, assists: 0 },
    lineup: [
      { name: "Mosquera", number: 1, position: "GK" },
      { name: "Murillo", number: 2, position: "DF" },
      { name: "Escobar", number: 4, position: "DF" },
      { name: "Anderson", number: 5, position: "DF" },
      { name: "Davis", number: 3, position: "DF" },
      { name: "Machado", number: 6, position: "DF" },
      { name: "Carrasquilla", number: 10, position: "MF" },
      { name: "Godoy", number: 8, position: "MF" },
      { name: "Aybar", number: 7, position: "MF" },
      { name: "Fajardo", number: 9, position: "FW" },
      { name: "Ismael", number: 11, position: "FW" },
    ],
  },
};

export function getTeamSquad(tla: string): TeamSquadData | null {
  return TEAM_SQUADS[tla] ?? null;
}
